export default {
  28: 'fa-solid fa-person-running',
  12: 'fa-solid fa-person-through-window',
  16: 'fa-solid fa-photo-film',
  35:"fa-regular fa-face-grin-squint-tears",
  80: 'fa-solid fa-handcuffs',
  99: 'fa-solid fa-video',
  18: 'fa-solid fa-masks-theater',
  10751: 'fa-solid fa-house-chimney',
  14: 'fa-solid fa-wand-sparkles',
  36: 'fa-solid fa-landmark',
  27: 'fa-solid fa-ghost',
  10402: 'fa-solid fa-guitar',
  9648: 'fa-solid fa-user-secret',
  10749: 'fa-regular fa-face-kiss-wink-heart',
  878: 'fa-solid fa-rocket',
  10770: 'fa-solid fa-tv',
  53: 'fa-solid fa-skull',
  10752: 'fa-solid fa-person-rifle',
  37: 'fa-solid fa-hat-cowboy',
};