export default [
  { id: "28", name: "Action", icon: "fa-solid fa-person-running" },
  { id: "12", name: "Adventure", icon: "fa-solid fa-person-through-window" },
  { id: "16", name: "Animation", icon: "fa-solid fa-photo-film" },
  { id: "35", name: "Comedy", icon: "fa-regular fa-face-grin-squint-tears" },
  { id: "80", name: "Crime", icon: "fa-solid fa-handcuffs" },
  { id: "99", name: "Documentary", icon: "fa-solid fa-video" },
  { id: "18", name: "Drama", icon: "fa-solid fa-masks-theater" },
  { id: "10751", name: "Family", icon: "fa-solid fa-house-chimney" },
  { id: "14", name: "Fantasy", icon: "fa-solid fa-wand-sparkles" },
  { id: "36", name: "History", icon: "fa-solid fa-landmark" },
  { id: "27", name: "Horror", icon: "fa-solid fa-ghost" },
  { id: "10402", name: "Music", icon: "fa-solid fa-guitar" },
  { id: "9648", name: "Mystery", icon: "fa-solid fa-user-secret" },
  { id: "10749", name: "Romance", icon: "fa-regular fa-face-kiss-wink-heart" },
  { id: "878", name: "Science Fiction", icon: "fa-solid fa-rocket" },
  { id: "10770", name: "TV Movie", icon: "fa-solid fa-tv" },
  { id: "53", name: "Thriller", icon: "fa-solid fa-skull" },
  { id: "10752", name: "War", icon: "fa-solid fa-person-rifle" },
  { id: "37", name: "Western", icon: "fa-solid fa-hat-cowboy" },
];